function A_drag = A_drag(drag_coeff,v_x,v_y,v_z,wEarth,x,y)
%A_DRAG
%    A_DRAG = A_DRAG(DRAG_COEFF,V_X,V_Y,V_Z,WEARTH,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Apr-2021 10:01:00

t5 = wEarth.*x;
t2 = -t5+v_y;
t3 = wEarth.*y;
t4 = t3+v_x;
t6 = t2.^2;
t7 = t4.^2;
t8 = v_z.^2;
t9 = t6+t7+t8;
t10 = 1.0./sqrt(t9);
t11 = sqrt(t9);
t12 = drag_coeff.*t2.*t4.*t10.*wEarth;
t13 = v_x.*2.0;
t14 = wEarth.*y.*2.0;
t15 = t13+t14;
t16 = v_y.*2.0;
t18 = wEarth.*x.*2.0;
t17 = t16-t18;
A_drag = reshape([t12,drag_coeff.*t11.*wEarth+drag_coeff.*t6.*t10.*wEarth,drag_coeff.*t2.*t10.*v_z.*wEarth,-drag_coeff.*t11.*wEarth-drag_coeff.*t7.*t10.*wEarth,-t12,-drag_coeff.*t4.*t10.*v_z.*wEarth,0.0,0.0,0.0,-drag_coeff.*t11-drag_coeff.*t4.*t10.*t15.*(1.0./2.0),drag_coeff.*t2.*t10.*t15.*(-1.0./2.0),drag_coeff.*t10.*t15.*v_z.*(-1.0./2.0),drag_coeff.*t4.*t10.*t17.*(-1.0./2.0),-drag_coeff.*t11-drag_coeff.*t2.*t10.*t17.*(1.0./2.0),drag_coeff.*t10.*t17.*v_z.*(-1.0./2.0),-drag_coeff.*t4.*t10.*v_z,-drag_coeff.*t2.*t10.*v_z,-drag_coeff.*t11-drag_coeff.*t8.*t10],[3,6]);
